# Generated by Django 4.1.3 on 2023-05-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_app.group",
            ),
        ),
        migrations.AlterField(
            model_name="authuser",
            name="msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="authuser",
            name="payment",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
