# Generated by Django 4.1.3 on 2023-05-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0003_group_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="created_by",
        ),
    ]
