# Generated by Django 4.1.3 on 2023-05-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0004_remove_group_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authuser",
            name="group",
        ),
        migrations.AddField(
            model_name="authuser",
            name="group_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="creted_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_app.authuser",
            ),
            preserve_default=False,
        ),
    ]
