# Generated by Django 4.1.3 on 2023-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0006_rename_creted_by_group_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="group_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
