# Generated by Django 4.1.3 on 2023-05-14 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment_app", "0008_alter_authuser_msg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuthUser",
            new_name="Expenses",
        ),
    ]
