# Generated by Django 4.1.3 on 2023-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0009_rename_authuser_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
