# Generated by Django 4.1.3 on 2023-05-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment_app", "0010_group_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="group_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_app.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
