# Generated by Django 4.1.3 on 2023-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0011_alter_expenses_group_name_alter_group_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="per_person",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
